name: background_locator_2
description: A Flutter plugin to request the location even if the app is killed. Sending the location to a dart function in background, also provide a meter filter
version: 2.0.6
homepage: https://github.com/Yukams/background_locator_fixed
issue_tracker: https://github.com/Yukams/background_locator_fixed/issues
platforms:
  android:
  ios:


environment:
  sdk: '>=2.12.0 <4.0.0'  # Update the lower bound to 2.12.0 to enable null safety
  flutter: ">=1.12.0"
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: yukams.app.background_locator_2
        pluginClass: BackgroundLocatorPlugin
      ios:
        pluginClass: BackgroundLocatorPlugin
